In [1]:
from DataCleaning import load_data, inspect_data, clean_data
from FeatureEngineering import feature_engineering,customer_features,rfm

In [2]:
path="Sample - Superstore 2019.csv"

In [3]:
df=load_data(path)

In [4]:
inspect_data(df)

Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 9996 entries, 0 to 9995
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          9994 non-null   float64
 1   Order ID        9994 non-null   str
 2   Order Date      9994 non-null   datetime64[us]
 3   Ship Date       9994 non-null   datetime64[us]
 4   Ship Mode       9994 non-null   str
 5   Customer ID     9994 non-null   str
 6   Customer Name   9994 non-null   str
 7   Segment         9994 non-null   str
 8   Country/Region  9994 non-null   str
 9   City            9994 non-null   str
 10  State           9994 non-null   str
 11  Postal Code     9983 non-null   float64
 12  Region          9994 non-null   str
 13  Product ID      9994 non-null   str
 14  Category        9994 non-null   str
 15  Sub-Category    9994 non-null   str
 16  Product Name    9994 non-null   str
 17  Sales           9994 non-null   float64
 18  Quantity        9994 non-null   float64
 19  Discount        9994 non-null   float64
 20  Profit          9994 non-null   float64
dtypes: datetime64[us](2), float64(6), str(13)
memory usage: 8.3 MB

First 5 Rows:
   Row ID        Order ID Order Date  Ship Date       Ship Mode Customer ID  \
0     1.0  CA-2018-152156 2018-11-08 2018-11-11    Second Class    CG-12520
1     2.0  CA-2018-152156 2018-11-08 2018-11-11    Second Class    CG-12520
2     3.0  CA-2018-138688 2018-06-12 2018-06-16    Second Class    DV-13045
3     4.0  US-2017-108966 2017-10-11 2017-10-18  Standard Class    SO-20335
4     5.0  US-2017-108966 2017-10-11 2017-10-18  Standard Class    SO-20335

     Customer Name    Segment Country/Region             City  ...  \
0      Claire Gute   Consumer  United States        Henderson  ...
1      Claire Gute   Consumer  United States        Henderson  ...
2  Darrin Van Huff  Corporate  United States      Los Angeles  ...
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...

  Postal Code  Region       Product ID         Category Sub-Category  \
0     42420.0   South  FUR-BO-10001798        Furniture    Bookcases
1     42420.0   South  FUR-CH-10000454        Furniture       Chairs
2     90036.0    West  OFF-LA-10000240  Office Supplies       Labels
3     33311.0   South  FUR-TA-10000577        Furniture       Tables
4     33311.0   South  OFF-ST-10000760  Office Supplies      Storage

                                        Product Name     Sales  Quantity  \
0                  Bush Somerset Collection Bookcase  261.9600       2.0
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400       3.0
2  Self-Adhesive Address Labels for Typewriters b...   14.6200       2.0
3      Bretford CR4500 Series Slim Rectangular Table  957.5775       5.0
4                     Eldon Fold 'N Roll Cart System   22.3680       2.0

   Discount    Profit
0      0.00   41.9136
1      0.00  219.5820
2      0.00    6.8714
3      0.45 -383.0310
4      0.20    2.5164

[5 rows x 21 columns]

In [5]:
df = clean_data(df)

Duplicate records found: 0

In [6]:

df=feature_engineering(df)

In [7]:
CustomerFeatures=customer_features(df)

In [8]:
CustomerFeatures

,Customer ID,order_count,total_spend,total_profit,avg_order_value,first_order,last_order,Customer Tenure Days
0,AA-10315,5,959.920,170.5439,106.657778,2016-03-31,2019-06-29,1185
1,AA-10375,9,556.410,162.3870,39.743571,2016-04-21,2019-12-11,1329
2,AA-10480,4,1790.512,435.8274,149.209333,2016-05-04,2019-04-15,1076
3,AA-10645,6,1088.700,242.7249,77.764286,2016-06-22,2019-11-05,1231
4,AB-10015,3,886.156,129.3465,147.692667,2016-02-18,2018-11-10,996
...,...,...,...,...,...,...,...,...
785,XP-21865,11,2374.658,621.2300,84.809214,2016-01-20,2019-11-17,1397
786,YC-21895,3,569.364,100.8334,113.872800,2016-11-17,2018-09-06,658
787,YS-21880,7,1926.876,255.4650,214.097333,2017-01-12,2019-08-18,948
788,ZC-21910,13,2047.373,125.4253,78.745115,2016-10-13,2019-11-06,1119
789,ZD-21925,5,669.984,197.6332,83.748000,2016-08-27,2019-06-11,1018

In [9]:
rfm=rfm(df)

In [10]:
rfm

    Customer ID  recency  frequency  monetary_value
0      AA-10315      185          5         959.920
1      AA-10375       20          9         556.410
2      AA-10480      260          4        1790.512
3      AA-10645       56          6        1088.700
4      AB-10015      416          3         886.156
..          ...      ...        ...             ...
785    XP-21865       44         11        2374.658
786    YC-21895      481          3         569.364
787    YS-21880      135          7        1926.876
788    ZC-21910       55         13        2047.373
789    ZD-21925      203          5         669.984

[790 rows x 4 columns]